notifications:
  email:
    recipients:
      - rich@flatcap.org
      - z+neomutt+github+travis@m0g.net
    on_success: change
    on_failure: always

sudo: false
dist: trusty

language: c
compiler: gcc
cache: ccache

addons:
  apt:
    packages:
      - python-software-properties
      - python-pip
      - libgpgme11-dev
      - libnotmuch-dev
      - libtokyocabinet-dev
      - libkyotocabinet-dev
      - libgdbm-dev
      - libdb-dev
      - liblmdb-dev
      - libqdbm-dev
      - libslang2-dev
      - libgnutls-dev
      - libssl-dev
      - libsasl2-dev
      - libgss-dev
      - xsltproc
      - lynx
      - docbook-simple
      - docbook-xsl
      - libxml2-utils
      - gettext
      - autopoint

git:
  depth: 3

env:
  global:
    - SOURCE_DIR="."
    - CONFIG_DIR="config"
    - LUAC_PATH="lua53"

before_install:
  - pip install hererocks cpp-coveralls
  - hererocks lua53 -l5.3 -rlatest --no-readline --cflags="-fPIC"
  - lua53/bin/luarocks install busted
  - lua53/bin/luarocks install luassert

install:
  - git clone --depth 1 https://github.com/neomutt/travis-build.git ${TRAVIS_BUILD_DIR}/config

script:
  - bash .ci/run_tests_unit.sh
  - bash .ci/run_tests_func.sh
  - bash .ci/run_tests_build.sh
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp' > /dev/null

