#!/bin/sh
#
# mailto-neomutt -- wrapper to use neomutt as mailto handler from Iceweasel
#
# If you want Iceweasel 3.x to use this wrapper for mailto URLs, go to Edit >
# Preferences > Applications, and set "mailto" to "/usr/lib/neomutt/mailto-neomutt".

exec x-terminal-emulator -e neomutt "$@"
